# -----------------------------
#            W I I C
# -----------------------------
# Made by ikeepcalm for UAPROJECT
# -----------------------------

# Multipliers for each rarity
rarities:
  COMMON: 1.0
  UNCOMMON: 1.5
  RARE: 2.0
  EPIC: 3.0

# Multipliers for each ore
ores:
  COAL_ORE: 0.0
  COPPER_ORE: 0.0
  IRON_ORE: 0.2
  GOLD_ORE: 0.5
  LAPIS_ORE: 0.3
  DIAMOND_ORE: 2.0
  EMERALD_ORE: 3.0
  REDSTONE_ORE: 0.1
  NETHER_QUARTZ_ORE: 0.2
  ANCIENT_DEBRIS: 5.0
  OTHER: 0.0

minimumValue: 0