name: WIIC
version: '${version}'
main: dev.ua.ikeepcalm.wiic.WIIC
api-version: '1.21'
depend: [ NBTAPI, LuckPerms ]
commands:
  wallet:
    description: Check your wallet debug information
    usage: /wallet
    permission: wiic.wallet
  convert:
    description: Convert your wallet to a new one
    usage: /convert
    permission: wiic.convert
  shatter:
    description: Shatter currency to lesser
    usage: /shatter
    permission: wiic.shatter
  summon-shopkeeper:
    description: Summon a shopkeeper
    usage: /summon-shopkeeper
    permission: wiic.spawnNPCs