name: WIIC
version: '${version}'
main: dev.ua.ikeepcalm.wiic.WIIC
api-version: '1.21'
depend: [ iConomyUnlocked, Vault ]
commands:
  wallet:
    description: Check your wallet debug information
    usage: /wallet
    permission: wiic.wallet
  shatter:
    description: Shatter currency to lesser
    usage: /shatter
    permission: wiic.shatter