name: WIIC
version: '${version}'
main: dev.ua.ikeepcalm.wiic.WIIC
api-version: '1.21'
depend: [ LuckPerms, Vault ]
commands:
  wallet:
    description: Check your wallet debug information
    usage: /wallet
    permission: wiic.wallet
  bind:
    description: Bind wallet item to player
    usage: /bind
    permission: wiic.bind
  shatter:
    description: Shatter currency to lesser
    usage: /shatter
    permission: wiic.shatter
  shopkeeper:
    description: Summon a shopkeeper
    usage: /shopkeeper
    permission: wiic.spawnNPCs